USE  "Whodo-hml"

CREATE TABLE [Authentication](
	Id					BIGINT IDENTITY(1, 1) NOT NULL,
	Email				VARCHAR(255) NOT NULL,
	[Password]			VARCHAR(MAX) NOT NULL,
	CreationDate		DATETIME NOT NULL,
	LastUpdateDate		DATETIME NULL,
	CONSTRAINT PK_Debit PRIMARY KEY(Id),
)
GO